// Code generated by "stringer -type=TokenType"; DO NOT EDIT

package lexer

import "fmt"

const _TokenType_name = "IdentifierOperatorMonoQuoteTriQuoteTerminatorCommentHexNumberDecimalCommaOpenClose"

var _TokenType_index = [...]uint8{0, 10, 18, 27, 35, 45, 52, 61, 68, 73, 77, 82}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
